package repository

import (
	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// DomainRecord is the GORM entity for the `domains` table.
//
// UUID columns are stored as TEXT (not the Postgres UUID type) so the same
// entity works in both Postgres and SQLite. The IDs themselves are RFC 4122
// v4 strings generated by BeforeCreate; no SQL DEFAULT is needed.
//
// Timestamps are stored as TEXT (RFC3339) so the same entity round-trips
// against either Postgres timestamptz or SQLite TEXT. Parse/format happens
// in toModel.
type DomainRecord struct {
	ID             string `gorm:"column:id;type:text;primary_key"`
	TenantID       string `gorm:"column:tenant_id;type:text;not null;index:idx_domains_tenant_id"`
	DomainID       string `gorm:"column:domain_id;type:text;not null;index:idx_domains_domain_id"`
	CurrentVersion string `gorm:"column:current_version;type:text;not null"`
	Description    string `gorm:"column:description;type:text"`
	Status         string `gorm:"column:status;type:text;not null;default:'active'"`
	CreatedAt      string `gorm:"column:created_at;type:text;not null"`
	UpdatedAt      string `gorm:"column:updated_at;type:text;not null"`
}

// BeforeCreate populates ID with a fresh UUID v4 if one isn't already set.
// Lets the same row work in Postgres + SQLite without per-DB defaults.
func (r *DomainRecord) BeforeCreate(tx *gorm.DB) error {
	if r.ID == "" {
		r.ID = uuid.NewString()
	}
	return nil
}

// TableName returns the table name for GORM.
func (DomainRecord) TableName() string { return "domains" }

// DomainVersionRecord is the GORM entity for the `domain_versions` table.
type DomainVersionRecord struct {
	ID          string         `gorm:"column:id;type:text;primary_key"`
	TenantID    string         `gorm:"column:tenant_id;type:text;not null"`
	DomainUUID  string         `gorm:"column:domain_uuid;type:text;not null;index:idx_domain_versions_domain_uuid"`
	Version     string         `gorm:"column:version;type:text;not null"`
	YAMLBody    string         `gorm:"column:yaml_body;type:text;not null"`
	JSONBody    datatypes.JSON `gorm:"column:json_body;type:text"`
	HarnessHash string         `gorm:"column:harness_hash;type:text;not null;default:''"`
	CreatedBy   *string        `gorm:"column:created_by;type:text"`
	CreatedAt   string         `gorm:"column:created_at;type:text;not null"`
}

// BeforeCreate populates ID with a fresh UUID v4 if one isn't already set.
func (r *DomainVersionRecord) BeforeCreate(tx *gorm.DB) error {
	if r.ID == "" {
		r.ID = uuid.NewString()
	}
	return nil
}

// TableName returns the table name for GORM.
func (DomainVersionRecord) TableName() string { return "domain_versions" }